id: P006641
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:12:20.826138
source_metadata:
  id: bdr:W28990
  title: རྗེ་ཡབ་སྲས་གསུམ་གྱི་ཚད་གཞུང་ཉེར་མཁོ་དང་གུང་ཐང་བློ་གྲོས་རྒྱ་མཚོའི་བསྡུས་གྲྭ
  author: ''
  volumes:
    a367cd2d990442718966658e780c5a3b:
      image_group_id: I4996
      title: ''
      volume_number: 1
      total_pages: 434
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
