id: IAB3EE93B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:11:32+00:00'
last_modified: '2022-06-08T05:50:46.722888+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28990
  title: རྗེ་ཡབ་སྲས་གསུམ་གྱི་ཚད་གཞུང་ཉེར་མཁོ་དང་གུང་ཐང་བློ་གྲོས་རྒྱ་མཚོའི་བསྡུས་གྲྭ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6609':
      image_group_id: I4996
      title: ''
      total_pages: 434
      order: 1
      base_file: 6609.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
